name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: "✨ Package updates"
    labels:
      - "renovate"
template: |
  ## What’s Changed

  $CHANGES

  ### Bug Fixes

  ### New Features

  ### Chores
